spring:
  application:
    name: querydsl

  profiles:
    active: local

  datasource:
    url: jdbc:h2:file:./data/h2/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true